# Generated by Django 3.2 on 2021-04-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_news_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='label',
            field=models.CharField(default='True', max_length=10),
        ),
    ]
