# Generated by Django 3.2 on 2021-04-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_news_detection', '0004_alter_newsarticle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('Business', 'Business'), ('Cars', 'Cars'), ('Entertainment', 'Entertainment'), ('Family', 'Family'), ('Health', 'Health'), ('Politics', 'Politics'), ('Religion', 'Religion'), ('Science', 'Science'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Travel', 'Travel'), ('Video', 'Video'), ('World', 'World')], default='Politics', max_length=100),
        ),
    ]
